# Generated by Django 2.2.2 on 2020-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='roomname',
            field=models.TextField(default='', max_length=100),
        ),
    ]
