# Generated by Django 2.2.2 on 2020-04-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200426_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='roomname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomname',
            field=models.CharField(max_length=100),
        ),
    ]
