# Generated by Django 2.2.2 on 2020-05-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_group_groupmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
