# Generated by Django 2.2 on 2020-07-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200603_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_type',
            field=models.CharField(default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='img_content',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
